config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'career', :to => 'static_pages#career'
  get 'team', :to => 'static_pages#team'
  resources :courses, :only => [:index, :show, :destroy] do
    resources :enrollments, :only => [:create, :destroy]
  end
  resources :lessons, :only => [:show, :destroy]
  resources :sections, :only => [:destroy]
  namespace :instructor do
    resources :lessons, :only => [:update]
    resources :sections, :only => [:update] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show, :update] do
      resources :sections, :only => [:create]
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @enrollment = Enrollment.find_by(course_id: @course.id, user_id: current_user.id)
  end


  def destroy
    @course = Course.find(params[:id])
    if @course.user != current_user
      render :text => 'Unauthorized', :status => :unauthorized and return
    end
    @course.destroy
    redirect_to root_path
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
before_action :authenticate_user!
before_action :require_authorized_for_current_course, :only => [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
      if current_course.user != current_user
        render(:text => "Unauthorized", :status => :unauthorized) && return
      end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :instrument, :description, :cost, :image)
  end


end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, :only => [:create]
  before_action :require_authorized_for_current_lesson, :only => [:update]


  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render :text => 'Updated!'
  end

  private

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, :only => [:create]
  before_action :require_authorized_for_current_section, :only => [:update]


  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render :text => 'Updated!'
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render(:text => "Unauthorized", :status => :unauthorized) && return
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render(:text => "Unauthorized", :status => :unauthorized) && return
    end
  end


  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <div class="text-center">
    <h1>Add A New Teacher</h1>
    <br />
    <br />
    <h3>- Teacher/Course Creation Disclaimer And Agreement -</h3>
    <br />
    <br />
    <p>By creating this course, the teacher or creator of this course is responsible for and expected to:</p>
      <ul>
        <li>1. Create and maintain your Stripe account.</li>
        <li>2. Handle chargebacks and all customer service issues.</li>
        <li>3. Is responsible for paying the Stripe fees and fees the platform charges.</li>
      </ul>
    <% if current_user.uid.nil? %>
      <%= link_to image_tag('blue-on-light.png'), user_omniauth_authorize_path(:stripe_connect) %>
      <br />
      <h4>Once you've connected with stripe to accept payments,</h4>
      <h4>you can finish setting up the course details here and press create.</h4>
    <% end %>
  </div>
  <br />
  <% if current_user.uid.present? %>
    <%= simple_form_for @course, :url => instructor_courses_path do |f| %>
      <%= f.input :title %>
      <%= f.input :instrument %>
      <%= f.input :description %>
      <%= f.input :cost %>
      <%= f.input :image %>
      <br />
      <%= f.submit "Create", :class => 'btn btn-primary' %>
      <br />
    <% end %>
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <div class="deletesection pull-right">
    <%= link_to course_path(current_course), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this course?'}, :class => 'btn btn-md btn-danger' do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  </div>
  <%= image_tag current_course.image, :class => 'img-responsive' %>
  <br />
  <%= link_to 'Preview As Student...', course_path(current_course), :class => 'btn btn-warning pull-right preview' %>
  <br class="clr" />

  <div class="text-center">
    <!-- Button trigger section modal -->
    <button class="newsection pull-left btn btn-primary btn-md" data-toggle="modal" data-target="#newSectionModal">
      <span class="glyphicon glyphicon-plus"></span>
      New Section
    </button>
  </div>
  <br class="clr" />
  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
    <li data-update-url="<%= instructor_section_path(section) %>" class="section-li">
      <div class="header">
        <span class="glyphicon glyphicon-option-vertical"></span>
        <%= section.title %>
      </div>
      <!-- Button trigger lesson modal -->
      <button class="newlesson btn btn-primary btn-sm pull-left new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
        <span class="glyphicon glyphicon-plus"></span>
      </button>
      <!-- Button delete section -->
      <div class="deletesection pull-right">
        <%= link_to section_path(section), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this section?'}, :class => 'btn btn-md btn-danger' do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </div>
      <br class="clr" />
      <br class="clr" />
      <ul class="lessons">
        <% section.lessons.rank(:row_order).each do |lesson| %>
          <li data-update-url="<%= instructor_lesson_path(lesson) %>">
            <div class="lessondot col-xs-1 pull-left">
              <br />
              <span class="glyphicon glyphicon-option-vertical"></span>
            </div>
            <div class="col-xs-11 text-center">
              <!-- delete lesson button -->
              <div class="delete pull-right">
                <%= link_to lesson_path(lesson), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this lesson?'}, :class => 'btn btn-xs btn-danger' do %>
                  <span class="glyphicon glyphicon-remove"></span>
                <% end %>
              </div>
              <p>
                <br class="clr" />
                <b><%= lesson.title %></b>
              </p>
              <p>
                <%= lesson.subtitle %>
              </p>
            </div>
            <br class="clr" />
          </li>
        <% end %>
      </ul>
      <br class="clr" />
    </li>
    <% end %>
  </ul>

</div>




<!-- Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newSectionModalLabel">Add A New Section</h4>

      </div>
      <%= simple_form_for @section, :url => instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add A Section", :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newLessonModal">Add A New Lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :subtitle %>
            <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add The Lesson", :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>