config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'career', :to => 'static_pages#career'
  get 'team', :to => 'static_pages#team'
  resources :courses, :only => [:index, :show, :destroy] do
    resources :enrollments, :only => [:create, :destroy]
  end
  resources :lessons, :only => [:show, :destroy]
  resources :sections, :only => [:destroy]
  namespace :instructor do
    resources :lessons, :only => [:update]
    resources :sections, :only => [:update] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show, :update] do
      resources :sections, :only => [:create]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qelody</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/5.0.2/video.js"></script>
</head>
<body>

  <div id="wrap">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Qelody", root_path, :class => 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Link</a></li> -->
            <li>
              <%= link_to 'View All Teachers', courses_path %>
            </li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
          <!-- <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Dashboard', dashboard_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>

            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info text-center"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger text-center"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>

  <br class="clr" />

  <div id="footer">
    <div class="container">
      <div class="col-xs-6 col-sm-3">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Profile', dashboard_path %>
      </div>
      <div class="col-xs-6 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', team_path %>
        <br />
        <%= link_to 'Careers', career_path %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-xs-6 col-sm-3">
        <b>Contact</b>
        <br />
        <%= mail_to "qelody@gmail.com" do %>
          Email
        <% end %>
      </div>
      <div class="col-xs-6 col-sm-3 social">
        <b>Social</b>
        <br />
        <%= link_to 'https://github.com/Mikeysax' do %>
          <%= image_tag 'github.png', :class => 'social-button' %>
        <% end %>
        <%= link_to 'https://plus.google.com/u/0/+MichaelFarrellM' do %>
          <%= image_tag 'google.png', :class => 'social-button' %>
        <% end %>
        <%= link_to 'http://mikeysax.com/' do %>
          <%= image_tag 'jekyll.png', :class => 'social-button' %>
        <% end %>
      </div>
    </div>
  </div>


</body>
</html>